### ISSUE TITLE
Replace custom structs (like PdfPoint) with .NetStandard ones (like Vector2)

### ISSUE THREAD

**Issue by MuziburRahman** [ixmilia/pdf#2]
The `System.Numerics.Vector2` is completely suited as a replacement of `PdfPoint`. As this is a .NetStandard library, it will be used with other libraries that use `Vector2` as primary point structure. Not having to make conversion from `PdfPoint` to` Vector2` and vice versa every time will reduce time, and will look nice.

**Comment by MuziburRahman** [comment]
I am willing to contribute and implement it if this issue is considered.

**Comment by brettfo** [comment]
I'd considered something similar in the past, but I think it's potentially more valuable to be able to specify points (X/Y pairs) with separate measurement units.  While odd, it could be very useful to locate a point on a page like so:

``` C#
var point = new PdfPoint(
    new PdfMeasurement(1.0, PdfMeasurementType.Inch),
    new PdfMeasurement(2.0, PdfMeasurementType.Mm));
```

If I adopted `Vector2` then that ability to specify different units would be lost.
