### ISSUE TITLE
Minimum explicit use of PdfMeasurement

### ISSUE THREAD

**Issue by mdmozibur** [ixmilia/pdf#3]
It will be nice if PdfMeasurement` is removed from every constructor and `float` or double id used instead. A nice example is:

**Instead of this:**
`new PdfLine(new PdfPoint(PdfMeasurement.Points(12.0), PdfMeasurement.Points(12.0)), new PdfPoint(PdfMeasurement.Points(48.0), PdfMeasurement.Points(48.0)));`

**make it this**:
`new PdfLine(new Vector2(12, 12), new Vector2(48, 48), PdfMeasurementType.Point);`

The idea is using one of the `PdfMeasurementType`s as default, so that it isn't required to mention the `PdfMeasurementType` every time. If it any other `PdfMeasurementType` is needed to be used, then the it will be explicitely mentioned.

**Comment by MuziburRahman** [comment]
I am willing to contribute and implement it if this issue is considered.

**Comment by brettfo** [comment]
I added a simpler constructor for `PdfPoint` similar to your suggestion in commit bbfbdb2de5957f80beb9e4149a59fb437ad58527.  It looks like this:

``` C#
var point = new PdfPoint(1.0, 2.0, PdfMeasurementType.Inch);
```

Instead of:

``` C#
var point = new PdfPoint(new PdfMeasurement(1.0, PdfMeasurementType.Mm), new PdfMeasurement(2.0, PdfMeasurementType.Mm));
```
